### ISSUE TITLE
Artifacts on mouse over gtk2 gui with kwin

### ISSUE THREAD

**Issue by nick87720z** [QtCurve/qtcurve#16]
Most interesting - it doesn't happen with compiz, as well as other gtk2 engines (adwaita, graybird).

![screen shot](http://wstaw.org/m/2013/12/27/qtcurve-gtk2-mouse-over-bug.png)

**Comment by yuyichao** [comment]
Could you please highlight where is the Artifacts on mouse over"?

If it only happens with kwin, is it sth related to shadows or background blur?

**Comment by nick87720z** [comment]
Oops, probably i should make it with english locale :)
Box 1 - Темп (en: tempo): one vertical thing before and after chain of widgets (slider, box and button), and between each two contacting widgets;
Box 2 - Размер (en: size): same as in box 1, but only for apper radio buttons row, and without prepending thing (only between and after);
Box 3 - Шаблон (en: template): just before yellow circle arrow button (checkbox has really bug size);
Above boxes: two things surrounding button "Старт" (startm uses playback start icon).

p.s. They are hard to notice with reduced size, open with 1:1 scale.

**Comment by nick87720z** [comment]
Doesn't appear anymore.
