### ISSUE TITLE
Cannot connect to X server during build

### ISSUE THREAD

**Issue by ralesk** [QtCurve/qtcurve#2]
I'm getting this with the 1.8.15 release tarball in our chrooted build environment:

<pre>[ 31%] Generating shadow7-png.h
gen-image-header: cannot connect to X server</pre>

This will probably be the case for many of the distros' package build systems.

**Comment by yuyichao** [comment]
Duplicated with https://github.com/QtCurve/qtcurve-qt4/pull/5
