### ISSUE TITLE
issue: kwin doesn't have transparency in context menu

### ISSUE THREAD

**Issue by nick87720z** [QtCurve/qtcurve#31]
First time i got it after kwin manual restart with --restart option (without to relogin after qtcurve from git was installed). But even after full relogin problem is here. Decoration itself is transparent. Did not test tooltip transparency yet, for me it has constant transparency even with fully opaque gradients.

**Comment by yuyichao** [comment]
Forgot to remove kwin from blacklist after the new way of doing transparent window is implemented. Fixed.
