### ISSUE TITLE
migrate titlebar and menubar

### ISSUE THREAD

**Issue by mojtaba82** [QtCurve/qtcurve#40]
Please migrate titlebar and menubar as when I hover mouse on title of window, menu of window appear.
Thanks alot.

**Comment by yuyichao** [comment]
Could you please explain what do you mean? (What settings are you using etc.)

**Comment by mojtaba82** [comment]
Excuse me for my bad English
I want you a new feature such that when mouse hover on application name part of titlebar, instead of application name of window, menu of window appear.
Thanks

**Comment by yuyichao** [comment]
What do you mean by menu of window?
Is it the KWin context menu?
![like this](http://wstaw.org/m/2014/01/09/plasma-desktopT11356.png)
And what's the difference between application name of titlebar and window?

**Comment by yuyichao** [comment]
It will be useful if you can highlight which part do you mean in a screenshot.

**Comment by mojtaba82** [comment]
For example, consider dolphin application
![dolphin3](https://f.cloud.github.com/assets/4151722/1878992/6470c708-7943-11e3-836e-c883661f240d.png)
I want to menubar 'File Edit View Go Tools Settings Help'  isn't shown but when mouse hover titlebar '/-Dolphin', Menubar appear in place of titlebar and titlebar disappear.

**Comment by yuyichao** [comment]
While I am not sure if it is possible to implement (very likely not), have you used KWin's appmenu support?

**Comment by mojtaba82** [comment]
Why not?
Like kdeplasma-applets-menubat exception you should use menu in titlebar instead of use menu as a widget.

**Comment by yuyichao** [comment]
Because titlebar is not a plasma applet.
And that's why I ask if you have used kwin's appmenu support before.

**Comment by mojtaba82** [comment]
You right, but in recent versions of kde menubar can add to titlebar as a button. I wish it was in expanded form not factor form

**Comment by yuyichao** [comment]
That is the appmenu support in KWin I mentioned. I remember Martin said somewhere else before that it is hard to do add it in "expanded form" and I doubt if it is possible to do it in decoration style.

**Comment by mojtaba82** [comment]
Thanks anyway for you'r responsibility

**Comment by mojtaba82** [comment]
Canonical implemented this feature (migrate titlebar and menubar) in ubuntu 14.04 unity. I wish you implement this feature.

**Comment by anion155** [comment]
There is a cool feature in Ubuntu 14.04 (I don't really know what WM there is used) to mix title bar and menu bar. Like so
http://cdn.arstechnica.net/wp-content/uploads/2014/02/unity-integrated-menus.png
It shows when mouse hover the title bar.
Is there any chance to someone can implement this?

**Comment by yuyichao** [comment]
As I said, there's not much I can do here. I'm almost 100% sure it will be a hack even if I implement it in a decoration style.

If you really want this feature, you should rather report it to kwin developer and try to convince them that it is possible.
