### ISSUE TITLE
When prepare gtk3 version of qtcurve

### ISSUE THREAD

**Issue by mojtaba82** [QtCurve/qtcurve#43]
Hi.
When prepare gtk3 version of qtcurve?

**Comment by yuyichao** [comment]
When prepare?

**Comment by yuyichao** [comment]
If you are asking about the progress about the Gtk3 port, there are some refactoring that have been done/is going on that are necessary for the port. However, there isn't a detailed plan for that yet.

There is also a [wiki page](https://github.com/QtCurve/qtcurve/wiki/Note-about-Gtk3-support) for this.

**Comment by mojtaba82** [comment]
I hope gtk3 port come soon
Thanks
