### ISSUE TITLE
Wrong "gtk-icon-sizes" string.

### ISSUE THREAD

**Issue by Kermit** [QtCurve/qtcurve#50]
Hi.
I have problem with really big icons in GTK apps (see attached screenshot).
![qtcurveiconbug](https://f.cloud.github.com/assets/62873/2058807/40f7eac8-8b85-11e3-939d-a3c8f721cba8.png)

When I run GTK app there is an error (for example for gtk-chtheme):

``` bash
"(gtk-chtheme:6073): Gtk-WARNING **: Error parsing gtk-icon-sizes string: 'gtk-small-toolbar=22,22:gtk-large-toolbar=32,32:gtk-dnd=16,16:gtk button=16,16:gtk-menu=32,32:gtk-dialog=oxygen,oxygen'"
```

I'm using QtCurve 1.8.18 in Archlinux.

**Comment by yuyichao** [comment]
Fixed in master
