### ISSUE TITLE
REGRESSION: Toolbar gradients with alpha broken

### ISSUE THREAD

**Issue by MilesBHuff** [QtCurve/qtcurve#52]
If the toolbar has a gradient with a step that has an alpha value of less than 100%, that step is displayed as black instead of transparent.

**Comment by MilesBHuff** [comment]
Bug new to 1.8.18, was unpresent in 1.8.17.

**Comment by MilesBHuff** [comment]
0% alpha at both steps: 
![toolbaralpha](https://f.cloud.github.com/assets/6566982/2060216/69943caa-8c04-11e3-9de0-48d5cd295e5d.png)
100% at first step, 0% at second step: 
![toolbaralpha2](https://f.cloud.github.com/assets/6566982/2060218/99fe8b48-8c04-11e3-850b-971155d114a2.png)

**Comment by yuyichao** [comment]
I guess this is a regression because of one of the bug fix. I have simply reverted it until I find a better solution.....

**Comment by MilesBHuff** [comment]
I hate when that happens; you fix one thing, and then it breaks another.  :\

Anyways, I can confirm toolbar gradient transparency is working correctly again on my end.

**Comment by yuyichao** [comment]
Me too....
I think this one is more important because the other problem only happens when using background transparency....
