### ISSUE TITLE
BUG: Tooltips have red glow

### ISSUE THREAD

**Issue by MilesBHuff** [QtCurve/qtcurve#54]
Some tooltips, particularly those in the QtCurve options dialogue, have a red glow around them, even when red is not used in the colour scheme or the qtcurve theme.  This glow color is also unconfigurable.

**Comment by MilesBHuff** [comment]
Bug new to 1.8.18, was unpresent in 1.8.17.

**Comment by yuyichao** [comment]
Can you add some screen shot with your bug reports?

Is the red glow in the tooltip shadow?

**Comment by MilesBHuff** [comment]
![rightclickmenu](https://f.cloud.github.com/assets/6566982/2060199/4d2b175c-8c02-11e3-80ba-e466a0f90891.png)
![selectionmenu](https://f.cloud.github.com/assets/6566982/2060200/4d2cec58-8c02-11e3-8796-dd8bf4209f14.png)
![tooltip](https://f.cloud.github.com/assets/6566982/2060201/4d2f0be6-8c02-11e3-91ff-a6f61b09f22a.png)

**Comment by MilesBHuff** [comment]
It's very odd.  It's definitely a new thing; the red glow wasn't there in 1.8.17.  
I've tried reinstalling several times, both the git version and the version in the Arch repos.  
When I go to 1.8.17, the problem goes away.

**Comment by yuyichao** [comment]
Is the glow still there if you turn off compositing?

**Comment by yuyichao** [comment]
~!@#$%^&_(_&^%$#@!~~!@#$%^&*****&^%$#@!~~!@#$%^&^%$#@!~!@
That was a typo............

Please test the referred commit.......

**Comment by MilesBHuff** [comment]
The bug is not there when compositing is off (since the glow is dependent on compositing)
I'm going to recompile qtcurve real fast; brb

**Comment by MilesBHuff** [comment]
Fixed!  :D
Good work!  :+1:

**Comment by yuyichao** [comment]
P.S. You probably have also noticed that the old one actually have a blue glow in the bottom right corner.....

**Comment by MilesBHuff** [comment]
I have!  I'd always just assumed it was something to do with kwin or my monitor.

**Comment by yuyichao** [comment]
.... Well, yes. That was a broken png file......

**Comment by MilesBHuff** [comment]
Huh.  Well, I'm glad you finally figured it out :)
btw, 虽然 我 是 美国 人, 会 说 点 普通话, 因为 在 大学 学了 一点 的.  可是 我 觉得 你 的 英文 更 好, 因为 我 的 中文 不 很 好. :p
我 很 累 现在, 去 睡觉 一下. 再见!
