### ISSUE TITLE
Background images drawn in place of background color/gradient instead of on top

### ISSUE THREAD

**Issue by Eltiech** [QtCurve/qtcurve#59]
I'm on 1.8.18-1.
Previously, I was able to configure everything to look like this. I have the window background set to a single color gradient, with alpha at 70ish%. Additionally, I have an image with a transparent background and a 10% alpha pattern of circles(attached below). The result previously was the following:
![bigger2](https://f.cloud.github.com/assets/3485966/2206438/a50de5be-9961-11e3-84ce-d31d7e469622.png)

The image being used(view it on a dark background, since it's mostly white/alpha)
![drnamenoback](https://f.cloud.github.com/assets/3485966/2206884/274e97fe-996b-11e3-982d-d5c208de5bba.png)

With recent updates(sorry, don't know the version I was on prior to updating, but it'd been a month or two since my last update), now, instead of drawing the image on top of the dark background, it's replacing it.
![snapshot1](https://f.cloud.github.com/assets/3485966/2206904/91945874-996b-11e3-866a-dd8c239e5bcb.png)

**Comment by yuyichao** [comment]
Duplicated https://github.com/QtCurve/qtcurve/issues/49
