### ISSUE TITLE
Blue glow and white lines

### ISSUE THREAD

**Issue by OskarKinomoto** [QtCurve/qtcurve#60]
I'm using QtCurve with dark colors. My problem is, that around context menus are white/gray lines and blue glow in right bottom corner which is shown on linked image. It only occurs with desktop effects on even when I disable every in "all effects" tab.
You can grab setting here: http://kde-look.org/content/show.php/Flat+QtCurve?content=163557 
Reproducible: Always 
Steps to Reproduce: 1. Use qt curve with dark theme on light theme is merely visible. 

kwin -v
Qt: 4.8.6 
KDE: 4.12.2 
KWin: 4.11.6

http://bugsfiles.kde.org/attachment.cgi?id=85270 - screen shot

**Comment by yuyichao** [comment]
Already fixed.
