### ISSUE TITLE
Heavy, blurry arrows in gtk

### ISSUE THREAD

**Issue by kachelaqa** [QtCurve/qtcurve#61]
Using version 1.8.18, the arrows in gtk have become heavy and blurry. This is in contrast with version 1.8.17, where the arrows looked the same as in non-gtk applications. Is there any way to revert to the old behaviour? Here's some screenshots to show what I mean.

Version 1.8.17
![qtcurve-arrows-1 8 17](https://cloud.githubusercontent.com/assets/1690389/2764876/5a46638a-ca1c-11e3-8207-cc58d6cde8b8.png)

Version 1.8.18
![qtcurve-arrows-1 8 18](https://cloud.githubusercontent.com/assets/1690389/2764877/5a48aa78-ca1c-11e3-83a7-5a2c8b1c6124.png)

**Comment by yuyichao** [comment]
.... I hate these Anti-alias business .....

= = .... seems that github automatically close the issue by parsing the commit message?
Anyway, should be fixed ..... PLZ test.

**Comment by kachelaqa** [comment]
Thanks. I will try later today and report back if it's not working for me.
