### ISSUE TITLE
When creating a new user with "widgetStyle=qtcurve" in kdeglobals QT-Curve always uses default theme

### ISSUE THREAD

**Issue by lots0logs** [QtCurve/qtcurve#70]
How can the theme be configured from the config files? (before user has logged in for the first time) Here is what I have in kdeglobals. It results in qtcurve being properly set as the widget style but the qtcurve theme is not affected. 

```
[General]
ColorScheme=Numix-Antergos
Name=Numix-Antergos
shadeSortColumn=true
widgetStyle=qtcurve
```

**Comment by yuyichao** [comment]
I haven't tested but you can try to copy the `~/.config/qtcurve` directory (or sth like `~/.config/qtcurvestyle` for old configure files.)

**Comment by lots0logs** [comment]
Hmm..I don't remember seeing that directory. I will check and let you know. Thanks!

**Comment by yuyichao** [comment]
Actually I have tested because this is exactly what I did when moving to my new computer a few weeks ago.

Close for now. Please feel free to reopen/report other issues if u have any further problems.
