### ISSUE TITLE
Border transparent

### ISSUE THREAD

**Issue by MilesBHuff** [QtCurve/qtcurve#76]
Fixed in update.

**Comment by yuyichao** [comment]
On Tue, Jul 22, 2014 at 2:00 AM, Maiya Liy Huff notifications@github.com
wrote:

> Not only have you not pushed critical fixes through to the official
> version (which should have been done via bugfix release the moment the bug
> with the glow was discovered), but you've broken the git version to where
> QtCurve does not even show up in the Application Appearance > Style menu of
> SystemSettings. Worse, titlebars are now broken, and the only way to use
> QtCurve currently is to set KDE to use GTK's theme, which does not work
> nearly as well as using QtCurve directly.

AFAIK, this should work as it always is and it is working here.

> Furthermore, there remain countless unresolved and outright ignored issues
> here on Github. I loved QtCurve, and then you ruined it. I'll be waiting
> until someone worth their salt comes along, using 1.8.17, the last good
> version.

AFAIK, the regression in 1.8.18 is reverted in git master. (although not
released, see below)

>  Also, with what you've been changing, you might want to consider a minor
> release instead of a bugfix release. When you break things, you don't make
> people think you've simply fixed a minor typo in text; you outright tell
> them that "Hey, this new version's a bit noticeably different than the
> last, so here's a minor release, because it would be irresponsible to
> publish it as a bugfix release."
> 
> I hate bashing on you over this because you're developing an open source
> project for free, and simply gifting your work to us. And I appreciate
> that. But please, do a good job with it; if you're going to haphazardly
> test things out, that's fine; but actually test them before publishing an
> official release. If you made a mistake in the

You are right here that I didn't tag a new release for the regression in
1.8.18 (delayed because of personal reasons but that is not an excuse).

I was planning to do a new release a week ago for the regression and some
other fixes but I was travelling last week and have just come back last
weekend. It will happen sometime soon (should be this week)

release, patch it and release a hotfix. Releases are not betas, and minor

> releases are not bugfix releases. If you compile QtCurve on your computer
> after tweaking some things, and it doesn't work, like, at all; don't put it
> on Git yet! Find what went wrong! Fix it, and _then_ upload to Git. It
> might be different if there were more contributors, but as the only one,
> you have to control the quality of your own work.

This is what I have always been doing.
The reason that there's regression sometime is that I cannot conver all
different option provided by qtcurve. (This is also why I was spliting some
common routines out but that's another story)

> And for goodness sakes, you've only got 42 reports of bugs. At least reply
> to us more often than not; ignoring us just makes us resent both you and
> the project, which is a shame, because QtCurve is really cool.
> 
> I wish you luck, and I'm always hoping every time that QtCurve is updated
> that it's even better than the last time. But until then, I'm going back to
> the last truly stable version (1.8.17).
> 
> I apologize for the length of this rant. I'm going to try to take some
> screenshots of what it looks like on my computer, and upload them for you.
> Perhaps the issues stem from your attempts to tweak the functioning of AA
> on Qt5?

If you have some screenshot that show regression after that last commit on
Qt5, it would be nice.
The change looks OK for the one case I was looking at but it was used in a
lot of different cases and I am not confident yet that it will not break
other places horribly.

**Comment by yuyichao** [comment]
BTW, if you really have problem loading the theme, please do open a detailed bug report here.

If you are using the kf5 version of systemsettings. It should recognize the theme but probably not the setting interface since that have not been ported yet. If you cannot see the theme at all, it would either be a bug of kf5 systemsettings or please try recompile and use the latest git version. Qt5 (~5.3) removes a API which was (mis-)used by QtCurve which was removed by the last pull request. ABI version bump in Qt5 would also require recompiling the theme.

**Comment by MilesBHuff** [comment]
I apologize for my harsh words.  I was rather frustrated in the moment, 
and took to expressing this in not the best way.  I appreciate your calm 
reply to me.
It was weird what happened; I had just updated QtCurve yesterday, and 
today was my first time restarting my computer (and X server) since 
then.  QtCurve seemed to disappear altogether, except in GTK apps, where 
it worked fine.  All Qt apps reverted to the CDE theme, and both QtCurve 
and Oxygen were missing from the SystemSettings dialogue.  I set KDE o 
use my GTK settings, which worked better than CDE in a pinch, but were 
no long-term solution.  I restarted my X server, and Kwin decorations, 
which had been fine before, were now bugged as well; it looked like it 
was trying to display the QtCurve window decoration, but there was just 
a partial outline of it, with no fill, just transparency.  The buttons, 
which I had set to be invisible, were visible, as well.  I wish I had 
screenshotted it right then, but I didn't, for some reason; I'm sorry 
about that.  I guess I was too occupied with trying to resolve the 
issue.  I updated my computer and restarted, but no luck, so I 
uninstalled the Git version (which I've only been using due to the 
regressions in the 'stable' one, but now that I have it working again, 
am considering sticking with so that I can help report issues as they 
come up) and reinstalled QtCurve 1.8.18, hoping it had been fixed. It 
hadn't, and I then wrote that scathing comment to you. Uninstalling the 
1.8.18 and reinstalling the Git version got everything working again.  
So, what I think happened is somehow, QtCurve's compatibility may have 
gotten broken with the version of Qt used by KDE 4.13.2, and when I 
recompiled it after having the latest Qt and KDE platform, it worked right.
Or, maybe it was just a glitch that affected only me, and if so, I'm 
doubly sorry for having bothered you.
But!  There is still the possiblity of there being some compatibility 
issue(s) with (an) earlier version(s) of (a) dependency/ies.  That would 
probably need to be noted in release notes if it's the case, but I'm not 
able to test it atm without going through hoops to downgrade my packages 
and recompile QtCurve-Git, so I hope my description alone helps resolve 
whatever issue(s), if any, this is related to.
I am currently on Arch Linux x86-64, running KDE platform 4.13.3, and 
using Qt4 v4.8.6 and Qt5 v5.3.1, if that's of any import.
Again, thanks for taking the time to reply to me.  :)
和 对不起 我 的 有点 麻烦 的 信息。
Regards,
Maiyli78

**Comment by yuyichao** [comment]
On Tue, Jul 22, 2014 at 3:22 AM, Maiya Liy Huff notifications@github.com
wrote:

> I apologize for my harsh words. I was rather frustrated in the moment,
> and took to expressing this in not the best way. I appreciate your calm
> reply to me.
> It was weird what happened; I had just updated QtCurve yesterday, and
> today was my first time restarting my computer (and X server) since
> then. QtCurve seemed to disappear altogether, except in GTK apps, where
> it worked fine. All Qt apps reverted to the CDE theme, and both QtCurve
> and Oxygen were missing from the SystemSettings dialogue. I set KDE o

Good to know that it is working again. The fact that oxygen is also missing
suggests that it's not really QtCurve's issue.

> use my GTK settings, which worked better than CDE in a pinch, but were
> no long-term solution. I restarted my X server, and Kwin decorations,
> which had been fine before, were now bugged as well; it looked like it
> was trying to display the QtCurve window decoration, but there was just
> a partial outline of it, with no fill, just transparency. The buttons,
> which I had set to be invisible, were visible, as well. I wish I had
> screenshotted it right then, but I didn't, for some reason; I'm sorry
> about that. I guess I was too occupied with trying to resolve the
> issue. I updated my computer and restarted, but no luck, so I
> uninstalled the Git version (which I've only been using due to the
> regressions in the 'stable' one, but now that I have it working again,
> am considering sticking with so that I can help report issues as they
> come up) and reinstalled QtCurve 1.8.18, hoping it had been fixed. It
> hadn't, and I then wrote that scathing comment to you. Uninstalling the
> 1.8.18 and reinstalling the Git version got everything working again.
> So, what I think happened is somehow, QtCurve's compatibility may have
> gotten broken with the version of Qt used by KDE 4.13.2, and when I
> recompiled it after having the latest Qt and KDE platform, it worked right.
> Or, maybe it was just a glitch that affected only me, and if so, I'm
> doubly sorry for having bothered you.
> But! There is still the possiblity of there being some compatibility
> issue(s) with (an) earlier version(s) of (a) dependency/ies. That would
> probably need to be noted in release notes if it's the case, but I'm not
> able to test it atm without going through hoops to downgrade my packages
> and recompile QtCurve-Git, so I hope my description alone helps resolve
> whatever issue(s), if any, this is related to.
> I am currently on Arch Linux x86-64, running KDE platform 4.13.3, and
> using Qt4 v4.8.6 and Qt5 v5.3.1, if that's of any import.
> Again, thanks for taking the time to reply to me. :)

I am also using Arch Linux and have just got the kde 4.13.3 update just
now. I'll check if there's any (most likely packaging) issue when I got a
time to re-login tomorrow.
