### ISSUE TITLE
QtCurve is dead?

### ISSUE THREAD

**Issue by meltylang** [QtCurve/qtcurve#81]
Last activity in KDE repo was pretty long ago.

**Comment by Infinality** [comment]
Looks like they don't use GitHub anymore:
https://github.com/QtCurve/qtcurve/blob/master/README.md

**Comment by meltylang** [comment]
I looked here:
https://quickgit.kde.org/?p=qtcurve.git

> Tags
> 23 months ago 1.8.18 For users

But looked again today, and there was commit 5 days ago. 
I hope it is good sign.
Can't update to KDE5 without proper QtCurve port — in debean, e.g no package with KWin decorations.

**Comment by Infinality** [comment]
Many distros already have qt5 packages that work with KDE5.  I'm using Fedora 23 / KDE 5, and these packages work for me:   http://koji.fedoraproject.org/koji/buildinfo?buildID=694397

EDIT:  Either way, you should be able to compile from source and pass the build flag to build the KDE 5 version.

**Comment by meltylang** [comment]
I'm use Debian, and yes, there is packages available, but for some reason they are lacking of Window Decorations (or windows borders, that thing with window caption, little app-icon and close/max/minimize buttons).
I already tried to build my custom package, but didn't found way to enable window decorations in KF5.
So I'm a bit nervous about project health and it future.

**Comment by Infinality** [comment]
Yeah, I'm pretty sure that the window decorations don't work.  They changed the API in KDE5.  Aurorae decorations still work though, and there are quite a few to choose from.
